const allPlayers = [
    {
      percentile: 99,
      name: "LeBron James",
      rank_change: 1,
      team: "Lakers",
      division: "West",
      team_placing: 2,
      Pos: "Power Forward",
      rank: 1,
    },
    {
      percentile: 97,
      name: "Kevin Durant",
      rank_change: -1,
      team: "Nets",
      division: "East",
      team_placing: 3,
      Pos: "Small Forward",
      rank: 2,
    },
    {
      percentile: 94,
      name: "Giannis Antetokounmpo",
      rank_change: 0,
      team: "Bucks",
      division: "East",
      team_placing: 1,
      Pos: "Power Forward",
      rank: 3,
    },
    {
      percentile: 92,
      name: "Stephen Curry",
      rank_change: 2,
      team: "Warriors",
      division: "West",
      team_placing: 4,
      Pos: "Point Guard",
      rank: 4,
    },
    {
      percentile: 90,
      name: "Kawhi Leonard",
      rank_change: -2,
      team: "Clippers",
      division: "West",
      team_placing: 5,
      Pos: "Small Forward",
      rank: 5,
    },
    {
      percentile: 88,
      name: "James Harden",
      rank_change: 3,
      team: "76ers",
      division: "East",
      team_placing: 2,
      Pos: "Shooting Guard",
      rank: 6,
    },
    {
      percentile: 83,
      name: "Anthony Davis",
      rank_change: -3,
      team: "Lakers",
      division: "West",
      team_placing: 2,
      Pos: "Power Forward",
      rank: 7,
    },
    {
      percentile: 80,
      name: "Luka Dončić",
      rank_change: 1,
      team: "Mavericks",
      division: "West",
      team_placing: 6,
      Pos: "Point Guard",
      rank: 8,
    },
    {
      percentile: 75,
      name: "Joel Embiid",
      rank_change: -1,
      team: "76ers",
      division: "East",
      team_placing: 2,
      Pos: "Center",
      rank: 9,
    },
    {
      percentile: 73,
      name: "Damian Lillard",
      rank_change: 4,
      team: "Trail Blazers",
      division: "West",
      team_placing: 8,
      Pos: "Point Guard",
      rank: 10,
    },
    {
      percentile: 73,
      name: "Nikola Jokić",
      rank_change: -4,
      team: "Nuggets",
      division: "West",
      team_placing: 7,
      Pos: "Center",
      rank: 11,
    },
    {
      percentile: 68,
      name: "Jayson Tatum",
      rank_change: 2,
      team: "Celtics",
      division: "East",
      team_placing: 4,
      Pos: "Small Forward",
      rank: 12,
    },
    {
      percentile: 64,
      name: "Jimmy Butler",
      rank_change: -2,
      team: "Heat",
      division: "East",
      team_placing: 5,
      Pos: "Small Forward",
      rank: 13,
    },
    {
      percentile: 62,
      name: "Kyrie Irving",
      rank_change: 3,
      team: "Nets",
      division: "East",
      team_placing: 3,
      Pos: "Point Guard",
      rank: 14,
    },
    {
      percentile: 59,
      name: "Devin Booker",
      rank_change: -3,
      team: "Suns",
      division: "West",
      team_placing: 3,
      Pos: "Shooting Guard",
      rank: 15,
    },
    {
      percentile: 56,
      name: "Paul George",
      rank_change: 1,
      team: "Clippers",
      division: "West",
      team_placing: 5,
      Pos: "Small Forward",
      rank: 16,
    },
    {
      percentile: 49,
      name: "Russell Westbrook",
      rank_change: -1,
      team: "Lakers",
      division: "West",
      team_placing: 2,
      Pos: "Point Guard",
      rank: 17,
    },
    {
      percentile: 42,
      name: "Karl-Anthony Towns",
      rank_change: 2,
      team: "Timberwolves",
      division: "West",
      team_placing: 9,
      Pos: "Center",
      rank: 18,
    },
    {
      percentile: 32,
      name: "Bradley Beal",
      rank_change: -2,
      team: "Wizards",
      division: "East",
      team_placing: 6,
      Pos: "Shooting Guard",
      rank: 19,
    },
    {
      percentile: 15,
      name: "Khris Middleton",
      rank_change: 1,
      team: "Bucks",
      division: "East",
      team_placing: 1,
      Pos: "Small Forward",
      rank: 20,
    }
  ];
  
  export default allPlayers;
  