const allTeams = [
    { name: "Lakers", standing: 1, division: "West", rank_change: 1, rank: 1 },
    { name: "Celtics", standing: 1, division: "East", rank_change: 1, rank: 2 },
    { name: "Warriors", standing: 2, division: "West", rank_change: 1, rank: 3 },
    { name: "Bucks", standing: 1, division: "East", rank_change: 1, rank: 4 },
    { name: "Clippers", standing: 3, division: "West", rank_change: 1, rank: 5 },
    { name: "76ers", standing: 2, division: "East", rank_change: 1, rank: 6 },
    { name: "Nets", standing: 3, division: "East", rank_change: 1, rank: 7 },
    { name: "Rockets", standing: 4, division: "West", rank_change: 1, rank: 8 },
    { name: "Heat", standing: 4, division: "East", rank_change: 1, rank: 9 },
    { name: "Nuggets", standing: 5, division: "West", rank_change: 1, rank: 10 },
    { name: "Raptors", standing: 5, division: "East", rank_change: 1, rank: 11 },
    { name: "Mavericks", standing: 6, division: "West", rank_change: 1, rank: 12 },
    { name: "Jazz", standing: 7, division: "West", rank_change: 1, rank: 13 },
    { name: "Trail Blazers", standing: 8, division: "West", rank_change: 1, rank: 14 },
    { name: "Suns", standing: 9, division: "West", rank_change: 1, rank: 15 },
    { name: "Thunder", standing: 10, division: "West", rank_change: 1, rank: 16 },
    { name: "Pacers", standing: 6, division: "East", rank_change: 1, rank: 17 },
    { name: "Grizzlies", standing: 11, division: "West", rank_change: 1, rank: 18 },
    { name: "Hawks", standing: 7, division: "East", rank_change: 1, rank: 19 },
    { name: "Wizards", standing: 8, division: "East", rank_change: 1, rank: 20 },
    { name: "Knicks", standing: 9, division: "East", rank_change: 1, rank: 21 },
    { name: "Spurs", standing: 12, division: "West", rank_change: 1, rank: 22 },
    { name: "Pistons", standing: 10, division: "East", rank_change: 1, rank: 23 },
    { name: "Magic", standing: 11, division: "East", rank_change: 1, rank: 24 },
    { name: "Kings", standing: 13, division: "West", rank_change: 1, rank: 25 },
    { name: "Hornets", standing: 12, division: "East", rank_change: 1, rank: 26 },
    { name: "Cavaliers", standing: 13, division: "East", rank_change: 1, rank: 27 },
    { name: "Bulls", standing: 14, division: "East", rank_change: 1, rank: 28 },
    { name: "Timberwolves", standing: 14, division: "West", rank_change: 1, rank: 29 },
    { name: "Pelicans", standing: 15, division: "West", rank_change: 1, rank: 30 }
  ];
  
  export default allTeams;
  